# Formula: libssh2
# C library implementing the SSH2 protocol

[package]
name = "libssh2"
version = "1.11.1"
description = "C library implementing the SSH2 protocol"
homepage = "https://libssh2.org"
license = "BSD-3-Clause"

[source]
url = "https://github.com/libssh2/libssh2/releases/download/libssh2-1.11.1/libssh2-1.11.1.tar.gz"
sha256 = "d9ec76cbe34db98eec3539fe2c899d26b0c837cb3eb466a56b0f109cabf658f7"
mirrors = [
    "https://libssh2.org/download/libssh2-1.11.1.tar.gz"
]

[bottle.macos-arm64]
url = "https://github.com/brew-rs/core/releases/download/libssh2-1.11.1/libssh2-1.11.1.macos-arm64.bottle.tar.gz"
sha256 = "e583cf76a0d41e3da578a666cc81b648ffa3461de890f954458dfa34d553fd80"

[bottle.macos-x86_64]
url = "https://github.com/brew-rs/core/releases/download/libssh2-1.11.1/libssh2-1.11.1.macos-x86_64.bottle.tar.gz"
sha256 = "9b13b3490f4c3ef451088962d69c2a59e9504c662d93e7a3445aa4ec02ef44cc"

[bottle.linux-x86_64]
url = "https://github.com/brew-rs/core/releases/download/libssh2-1.11.1/libssh2-1.11.1.linux-x86_64.bottle.tar.gz"
sha256 = "4648c20291fbaa7e62b1feee2b08eb3469ba0e6cd9b19e4402059956934324f0"

[dependencies]
runtime = ["openssl"]
build = ["cmake", "pkg-config"]

[build]
commands = [
    "cmake -S . -B build -DCMAKE_INSTALL_PREFIX=$PREFIX -DBUILD_SHARED_LIBS=ON -DCRYPTO_BACKEND=OpenSSL -DENABLE_ZLIB_COMPRESSION=ON",
    "cmake --build build -j $NCPU",
    "cmake --install build"
]
