# Formula: openssl
# Cryptography and SSL/TLS toolkit

[package]
name = "openssl"
version = "3.6.2"
description = "Cryptography and SSL/TLS toolkit"
homepage = "https://openssl-library.org"
license = "Apache-2.0"

[source]
url = "https://github.com/openssl/openssl/releases/download/openssl-3.6.2/openssl-3.6.2.tar.gz"
sha256 = "aaf51a1fe064384f811daeaeb4ec4dce7340ec8bd893027eee676af31e83a04f"
mirrors = [
    "https://www.openssl.org/source/openssl-3.6.2.tar.gz"
]

[bottle.macos-arm64]
url = "https://github.com/brew-rs/core/releases/download/openssl-3.6.2/openssl-3.6.2.macos-arm64.bottle.tar.gz"
sha256 = "09ed1ee8a553986186e3a422d7697dd81bc203d7a97decf2fbd4404ba7ca1b72"

[bottle.macos-x86_64]
url = "https://github.com/brew-rs/core/releases/download/openssl-3.6.2/openssl-3.6.2.macos-x86_64.bottle.tar.gz"
sha256 = "a9f7195a1947976c05fed917d7d017ca00859e7531a141182296a8ff49ffef67"

[bottle.linux-x86_64]
url = "https://github.com/brew-rs/core/releases/download/openssl-3.6.2/openssl-3.6.2.linux-x86_64.bottle.tar.gz"
sha256 = "f9a7242907b1c2e713ca4fc894d0f737e49578830ae286b5736f18daf4ab5b9f"

[dependencies]
runtime = ["zlib"]
build = ["perl", "make"]

[build]
commands = [
    "./Configure --prefix=$PREFIX --openssldir=$PREFIX/etc/openssl --libdir=lib shared zlib",
    "make -j$NCPU",
    "make install"
]

[build.env]
KERNEL_BITS = "64"
